### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by bjsi** [muhajirdev/rem-wiki-plugin#2]
https://github.com/muhajirdev/rem-wiki-plugin/blob/75cc4c000a0b7ce45c0ae040e83312729660e202/src/widgets/index.tsx#L31-L33

You can remove this code registering the sample widget and the sample_widget.tsx file.

https://github.com/muhajirdev/rem-wiki-plugin/blob/75cc4c000a0b7ce45c0ae040e83312729660e202/src/utils/build-json-tree.ts#L34-L35

Let me know the desired behavior for portals and I can help you code it, or add new API methods if required :+1: 

- [ ] Could you expand the readme to explain how to use the plugin and how it works.

**Comment by bjsi** [comment]
Will the code for the https://rem.wiki/ website be open source?

**Comment by muhajirdev** [comment]
- I updated the `registerWidget` part. The widget is now usable
- And the portal part resolved as well :)
- README is updated as well 🥳 



- Open source rem.wiki. I am considering to. I'll probably clean it up a bit.

**Comment by muhajirdev** [comment]
Thanks alot for reviewing @bjsi
