### ISSUE TITLE
Make username reactive

### ISSUE THREAD

**Issue by bjsi** [muhajirdev/rem-wiki-plugin#4]
https://github.com/muhajirdev/rem-wiki-plugin/blob/9aba81d1797ac118a512dc140746e8381ef61e3e/src/widgets/publication_sidebar.tsx#L31

Should be `let username = useTracker((reactivePlugin) => reactivePlugin.settings.getSetting<string>('username'));`. Now it will update without needing to close and reopen the sidebar.

**Comment by muhajirdev** [comment]
I see, thank you

fixed
